import {
  AlertTriangle,
  BadgeCheck,
  CircleDashed,
  FileQuestion,
  MinusCircle,
  type LucideIcon,
} from "lucide-react";

export type ComplianceStatus = "VERIFIED" | "CONFLICT" | "PENDING" | "EXEMPT" | "OFFICER REVIEW";
export type RiskLevel = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";

export const statusMeta: Record<ComplianceStatus, { icon: LucideIcon; className: string; label: string; helper: string }> = {
  VERIFIED: {
    icon: BadgeCheck,
    className: "border-verified/25 bg-verified/10 text-verified",
    label: "Verified",
    helper: "Evidence matched the applicable rule.",
  },
  CONFLICT: {
    icon: AlertTriangle,
    className: "border-conflict/25 bg-conflict/10 text-conflict",
    label: "Conflict",
    helper: "A rule could not be satisfied from the available evidence.",
  },
  PENDING: {
    icon: CircleDashed,
    className: "border-warning/25 bg-warning/10 text-warning",
    label: "Pending",
    helper: "Evidence or officer action is still required.",
  },
  EXEMPT: {
    icon: MinusCircle,
    className: "border-slate-300 bg-slate-100 text-slate-700",
    label: "Exempt",
    helper: "The requirement is not applicable for this bidder.",
  },
  "OFFICER REVIEW": {
    icon: FileQuestion,
    className: "border-review/25 bg-review/10 text-review",
    label: "Officer Review",
    helper: "A procurement officer must review the finding.",
  },
};

export const riskClass: Record<RiskLevel, string> = {
  LOW: "border-verified/25 bg-verified/10 text-verified",
  MEDIUM: "border-warning/25 bg-warning/10 text-warning",
  HIGH: "border-orange-300 bg-orange-50 text-orange-700",
  CRITICAL: "border-conflict/25 bg-conflict/10 text-conflict",
};

export const tenders = [
  {
    id: "GEM/2026/B/CPCL/1041",
    title: "Supply of Flameproof Motors for Refinery Unit III",
    type: "Goods",
    created: "02 Sep 2026",
    bidders: 8,
    requirements: 24,
    compliance: 78,
    risk: "MEDIUM" as RiskLevel,
    status: "Under Review",
    updated: "06 Sep 2026, 09:22 AM",
  },
  {
    id: "GEM/2026/B/CPCL/0988",
    title: "Annual Maintenance of Industrial UPS Systems",
    type: "Services",
    created: "26 Aug 2026",
    bidders: 5,
    requirements: 19,
    compliance: 92,
    risk: "LOW" as RiskLevel,
    status: "Active",
    updated: "05 Sep 2026, 04:30 PM",
  },
  {
    id: "GEM/2026/B/CPCL/1060",
    title: "Procurement of Stainless Steel Pipes and Fittings",
    type: "Goods",
    created: "04 Sep 2026",
    bidders: 11,
    requirements: 27,
    compliance: 66,
    risk: "HIGH" as RiskLevel,
    status: "High Risk",
    updated: "06 Sep 2026, 10:08 AM",
  },
  {
    id: "GEM/2026/B/CPCL/0931",
    title: "Calibration Services for Laboratory Instruments",
    type: "Services",
    created: "16 Aug 2026",
    bidders: 4,
    requirements: 16,
    compliance: 100,
    risk: "LOW" as RiskLevel,
    status: "Completed",
    updated: "01 Sep 2026, 02:18 PM",
  },
  {
    id: "GEM/2026/B/CPCL/1054",
    title: "Safety Valves for Process Equipment",
    type: "Goods",
    created: "03 Sep 2026",
    bidders: 7,
    requirements: 22,
    compliance: 73,
    risk: "MEDIUM" as RiskLevel,
    status: "Under Review",
    updated: "06 Sep 2026, 08:55 AM",
  },
];

export const bidders = [
  {
    id: "shakti",
    name: "Shakti Industrial Systems Pvt. Ltd.",
    sellerId: "GEM/SELLER/IN/26/48192",
    pan: "AAJCS4821K",
    gstin: "33AAJCS4821K1Z8",
    udyam: "UDYAM-TN-02-0048192",
    cin: "U29190TN2018PTC148192",
    compliance: 82,
    risk: "MEDIUM" as RiskLevel,
    docs: 14,
    status: "OFFICER REVIEW" as ComplianceStatus,
  },
  {
    id: "bharat",
    name: "Bharat Precision Technologies",
    sellerId: "GEM/SELLER/IN/26/31580",
    pan: "AAKFB3158M",
    gstin: "29AAKFB3158M1Z2",
    udyam: "UDYAM-KR-03-0031580",
    cin: "U31909KA2016PTC131580",
    compliance: 94,
    risk: "LOW" as RiskLevel,
    docs: 12,
    status: "VERIFIED" as ComplianceStatus,
  },
  {
    id: "aarav",
    name: "Aarav Infrastructure Solutions",
    sellerId: "GEM/SELLER/IN/26/74206",
    pan: "ABFFA7420J",
    gstin: "27ABFFA7420J1ZX",
    udyam: "UDYAM-MH-18-0074206",
    cin: "U45209MH2019PTC174206",
    compliance: 71,
    risk: "HIGH" as RiskLevel,
    docs: 10,
    status: "CONFLICT" as ComplianceStatus,
  },
  {
    id: "national",
    name: "National Engineering Works",
    sellerId: "GEM/SELLER/IN/26/90641",
    pan: "AABFN9064H",
    gstin: "09AABFN9064H1ZT",
    udyam: "UDYAM-UP-29-0090641",
    cin: "U28999UP2014PTC190641",
    compliance: 88,
    risk: "LOW" as RiskLevel,
    docs: 13,
    status: "VERIFIED" as ComplianceStatus,
  },
  {
    id: "dakshin",
    name: "Dakshin Process Controls Pvt. Ltd.",
    sellerId: "GEM/SELLER/IN/26/59012",
    pan: "AAFCD5901R",
    gstin: "33AAFCD5901R1ZP",
    udyam: "UDYAM-TN-24-0059012",
    cin: "U31200TN2020PTC159012",
    compliance: 79,
    risk: "MEDIUM" as RiskLevel,
    docs: 11,
    status: "PENDING" as ComplianceStatus,
  },
  {
    id: "surya",
    name: "Surya Valves and Controls",
    sellerId: "GEM/SELLER/IN/26/22841",
    pan: "ABNFS2284C",
    gstin: "24ABNFS2284C1ZE",
    udyam: "UDYAM-GJ-11-0022841",
    cin: "U29120GJ2015PTC122841",
    compliance: 84,
    risk: "MEDIUM" as RiskLevel,
    docs: 9,
    status: "OFFICER REVIEW" as ComplianceStatus,
  },
  {
    id: "triveni",
    name: "Triveni Mechanical Fabricators",
    sellerId: "GEM/SELLER/IN/26/88140",
    pan: "AAFFT8814L",
    gstin: "36AAFFT8814L1ZS",
    udyam: "UDYAM-TS-07-0088140",
    cin: "U28112TG2017PTC188140",
    compliance: 61,
    risk: "HIGH" as RiskLevel,
    docs: 8,
    status: "CONFLICT" as ComplianceStatus,
  },
  {
    id: "kaveri",
    name: "Kaveri Electrical Assemblies",
    sellerId: "GEM/SELLER/IN/26/11974",
    pan: "AAJFK1197P",
    gstin: "33AAJFK1197P1ZU",
    udyam: "UDYAM-TN-12-0011974",
    cin: "U31909TN2021PTC111974",
    compliance: 90,
    risk: "LOW" as RiskLevel,
    docs: 12,
    status: "VERIFIED" as ComplianceStatus,
  },
];

export const requirements = [
  ["REQ-001", "Valid BIS certification for offered product", "Mandatory", "Clause 4.2", "Manufacturer + product + model + standard + validity must match.", "BIS Certificate", "Government Portal Verification", "OFFICER REVIEW"],
  ["REQ-002", "GST registration must be active", "Mandatory", "GTC 3.1", "GSTIN must map to bidder legal entity and active status.", "GST registration record", "Government API", "PENDING"],
  ["REQ-003", "Bidder must not be debarred", "Mandatory", "GTC 5.4", "No active debarment should exist on tender date.", "GeM seller record", "Government Portal Verification", "VERIFIED"],
  ["REQ-004", "Udyam MSE status for EMD exemption", "Conditional", "ATC 8.1", "MSE category must be valid for exemption claim.", "Udyam certificate", "Government Portal Verification", "EXEMPT"],
  ["REQ-005", "Average annual turnover above INR 2 crore", "Mandatory", "ATC 6.3", "Audited turnover must meet threshold for last three years.", "CA certificate", "Bidder Submitted Document", "VERIFIED"],
  ["REQ-006", "Make in India local content declaration", "Mandatory", "STC 2.2", "Class-I/Class-II declaration must be signed and applicable.", "MII declaration", "Bidder Submitted Document", "OFFICER REVIEW"],
  ["REQ-007", "OEM authorization for offered model", "Conditional", "Technical 9.4", "Authorization must reference the tender and product model.", "OEM letter", "Bidder Submitted Document", "VERIFIED"],
  ["REQ-008", "EPFO registration where labour deployment applies", "Conditional", "GTC 9.2", "EPFO code should be active when manpower services apply.", "EPFO record", "Government Portal Verification", "PENDING"],
  ["REQ-009", "ESIC registration where applicable", "Conditional", "GTC 9.3", "ESIC registration must be active for applicable bidders.", "ESIC record", "Government Portal Verification", "PENDING"],
  ["REQ-010", "Experience in refinery-grade industrial supply", "Mandatory", "ATC 5.1", "Purchase orders must match category and value threshold.", "PO and completion certificate", "Bidder Submitted Document", "VERIFIED"],
  ["REQ-011", "EMD instrument validity", "Conditional", "ATC 8.2", "If no valid exemption, EMD must meet amount and validity.", "Bank guarantee", "Bidder Submitted Document", "EXEMPT"],
  ["REQ-012", "PAN and GST identity consistency", "Mandatory", "GTC 2.1", "PAN embedded in GSTIN must match bidder PAN.", "PAN and GST records", "Government API", "VERIFIED"],
  ["REQ-013", "MCA company status active", "Mandatory", "GTC 2.4", "Company status must be active on bid submission date.", "MCA master data", "Government Portal Verification", "VERIFIED"],
  ["REQ-014", "Startup India exemption eligibility", "Conditional", "ATC 8.4", "DPIIT recognition must be valid if claimed.", "DPIIT certificate", "Government Portal Verification", "PENDING"],
  ["REQ-015", "NSIC exemption eligibility", "Conditional", "ATC 8.5", "NSIC certificate must cover tender category.", "NSIC certificate", "Bidder Submitted Document", "PENDING"],
  ["REQ-016", "Technical datasheet submitted", "Mandatory", "Technical 3.2", "Datasheet must include offered model and ratings.", "Datasheet", "Bidder Submitted Document", "VERIFIED"],
  ["REQ-017", "Warranty undertaking", "Mandatory", "STC 4.1", "Warranty period must satisfy tender terms.", "Undertaking", "Bidder Submitted Document", "VERIFIED"],
  ["REQ-018", "Bid validity", "Mandatory", "GTC 6.1", "Offer validity must satisfy minimum period.", "Bid form", "Bidder Submitted Document", "VERIFIED"],
  ["REQ-019", "Quality assurance plan", "Informational", "Technical 11.1", "Plan should include inspection and test stages.", "QA plan", "Bidder Submitted Document", "PENDING"],
  ["REQ-020", "Delivery schedule compliance", "Mandatory", "STC 7.1", "Quoted delivery must be within allowed window.", "Commercial bid", "Bidder Submitted Document", "VERIFIED"],
  ["REQ-021", "Integrity pact acceptance", "Mandatory", "GTC 11.2", "Signed acceptance must be present.", "Integrity pact", "Bidder Submitted Document", "VERIFIED"],
  ["REQ-022", "Bank details verified", "Informational", "GTC 12.4", "Account details should match bidder legal name.", "Cancelled cheque", "Officer Verified", "OFFICER REVIEW"],
  ["REQ-023", "Factory test certificate availability", "Conditional", "Technical 12.2", "Certificate must be submitted before dispatch.", "FTC sample", "Bidder Submitted Document", "PENDING"],
  ["REQ-024", "Land border declaration", "Mandatory", "GTC 14.1", "Declaration must be submitted and signed.", "Declaration", "Bidder Submitted Document", "VERIFIED"],
] as const;

export const sourceCards = [
  ["GST", "PENDING", "06 Sep 2026, 09:41 AM", "Government API - Mock verification", "Tier 1 - Authoritative API"],
  ["Udyam", "VERIFIED", "06 Sep 2026, 09:38 AM", "Government Portal Verification - simulated", "Tier 2 - Official Verification"],
  ["MCA", "VERIFIED", "05 Sep 2026, 05:16 PM", "Government Portal Verification - simulated", "Tier 2 - Official Verification"],
  ["BIS", "OFFICER REVIEW", "06 Sep 2026, 09:46 AM", "Government Portal Verification - simulated", "Tier 2 - Official Verification"],
  ["DPIIT", "PENDING", "Integration pending", "Manual verification", "Tier 3 - Bidder Document"],
  ["EPFO", "PENDING", "Integration pending", "Manual verification", "Tier 3 - Bidder Document"],
  ["ESIC", "PENDING", "Integration pending", "Manual verification", "Tier 3 - Bidder Document"],
  ["GeM", "VERIFIED", "06 Sep 2026, 09:30 AM", "Government Portal Verification - simulated", "Tier 2 - Official Verification"],
  ["DigiLocker", "PENDING", "Not connected", "Mock verification", "Tier 3 - Bidder Document"],
] as const;

export const findings = [
  {
    id: "FND-104",
    title: "BIS certificate model mismatch",
    bidder: "Shakti Industrial Systems Pvt. Ltd.",
    tender: "GEM/2026/B/CPCL/1041",
    severity: "HIGH" as RiskLevel,
    issue: "BIS model does not match tendered model.",
    rule: "BIS certification must cover the offered product/model.",
    evidence: "BIS Licence No. BIS/2026/12345 covers model X100; tender offer specifies X110.",
    source: "BIS Official Verification - simulated",
    confidence: 94,
    checked: "06 Sep 2026, 09:46 AM",
    action: "Officer review required",
  },
  {
    id: "FND-097",
    title: "GST verification pending",
    bidder: "Sharma Industrial Components",
    tender: "GEM/2026/B/CPCL/1060",
    severity: "MEDIUM" as RiskLevel,
    issue: "GST status has not been verified from an authoritative source.",
    rule: "GST registration must be active and map to bidder PAN.",
    evidence: "Bidder submitted GST certificate only.",
    source: "Bidder Submitted Document",
    confidence: 72,
    checked: "06 Sep 2026, 08:50 AM",
    action: "Complete manual verification",
  },
  {
    id: "FND-088",
    title: "Identity name variation",
    bidder: "Aarav Infrastructure Solutions",
    tender: "GEM/2026/B/CPCL/1054",
    severity: "MEDIUM" as RiskLevel,
    issue: "Potential identity discrepancy detected. Officer review required.",
    rule: "PAN, GSTIN, Udyam and GeM Seller ID should resolve to the same legal entity.",
    evidence: "GST legal name includes 'LLP' while bid form omits the suffix.",
    source: "Government API - Mock verification",
    confidence: 86,
    checked: "05 Sep 2026, 04:02 PM",
    action: "Review identity evidence",
  },
  {
    id: "FND-081",
    title: "MII declaration needs confirmation",
    bidder: "Surya Valves and Controls",
    tender: "GEM/2026/B/CPCL/1041",
    severity: "LOW" as RiskLevel,
    issue: "Local content declaration is present but annexure reference is missing.",
    rule: "Make in India declaration must state local content class and be signed.",
    evidence: "Signed declaration, missing annexure A reference.",
    source: "Bidder Submitted Document",
    confidence: 81,
    checked: "05 Sep 2026, 03:35 PM",
    action: "Request clarification if needed",
  },
];

export const auditEvents = [
  ["09:32 AM", "Procurement Officer", "Tender uploaded", "Officer workspace", "", "GeM Bid and ATC documents added"],
  ["09:35 AM", "AI Document Engine", "Requirements extracted", "AI Extraction", "0 requirements", "24 requirements"],
  ["09:41 AM", "Verification Service", "GST evidence retrieved", "Government API - Mock verification", "Pending", "Evidence available"],
  ["09:46 AM", "Rule Engine", "BIS mismatch detected", "Government Portal Verification - simulated", "Verified", "Officer Review"],
  ["10:02 AM", "Procurement Officer", "Finding reviewed", "Officer Review", "Unread", "Reviewed"],
  ["10:08 AM", "Procurement Officer", "Clarification requested", "Officer Review", "Officer Review", "Clarification Required"],
] as const;

export const evidenceRecord = {
  requirement: "BIS certification required",
  rule: "Licence must cover manufacturer, product model, standard and validity.",
  evidence: "BIS Licence No: BIS/2026/12345",
  source: "BIS Official Verification - simulated",
  retrieved: "04 Sep 2026, 11:42 AM",
  confidence: 98,
  result: "Model mismatch detected",
};
